Select2 removal
lobsters/lobsters pull request #1125
Opened 2022-08-23 21:17 UTC by ymeynot45

**This pull request is a work in progress**
I wanted to keep you all updated as to how the jQuery removal was going. 
I have chosen [TomSelect](https://tom-select.js.org/) to replace select2.
The difficulty has come where TomSelect uses divs and select2 uses li.  So the css has required a lot of manhandling.
I am looking for thoughts from anyone who is interested in this project.  I will continue to work through it.  I hope this update is useful for anyone else working on the site.

**Currently known errors:**
- positioning of elements around the story tags when submitting a story.
- color of elements around the story tags when submitting a story.
- text styling on the drop down to choose tags when submitting a story.
- what information is displayed on the chosen tags.

2022-08-26 21:03 UTC, ymeynot45 commented
I'm in a holding pattern while I wait for the TomSelect creator to resolve a small bug I found.  He has resolved multiple issues in the last week, so I hope for a quick turn around.

2022-08-27 00:50 UTC, pushcx requested changes
Some notes on the work in progress. Mostly this is me being particular about comments, of all the nitpicky things.

2022-08-29 18:41 UTC, ymeynot45 commented on app/assets/stylesheets/application.css.erb
> +  margin-left: 0;
I was able to move half of them and delete the doubles, but some of them break the location of the button if you try to move them to ::after.

2022-08-29 18:51 UTC, ymeynot45 commented on app/assets/stylesheets/application.css.erb
> +  border: 1px solid var(--color-box-border);
Sigh* the eternal battle continues.  The line above was a tab and the line below was 2 spaces, so this was no-mans land?
Did you want me to make them all tabs or all 2 spances?

2022-08-29 19:08 UTC, ymeynot45 commented on app/assets/javascripts/application.js.erb
> +        Lobster.tom.addItem(tag.toLowerCase());
Any time you add a tag from the list of possible tags, TomSelect removes it from the list.
Then when TomSelect can't find the tag in the list it won't add it. 
If you add a tag and then delete it, TomSelect puts it back into the list.

2022-10-24 02:02 UTC, pushcx commented
Thank you for addressing everything and carrying this project through. I'm going to merge and deploy now while traffic is low.

2022-10-24 02:03 UTC, merged