Feature/rack attack cache
lobsters/lobsters pull request #1406
Opened 2024-12-23 08:47 UTC by rahul1990gupta

It took a shot at the issue https://github.com/lobsters/lobsters/issues/1401
which requires using sqlite3 based solid cache for rack_attack middleware.

# Steps for installation 
- `bundle install` will install solid_cache and sqlite3 geme. 
- `rails solid_cache:install` will create `config/cache.yml` and generate `cache_schema.rb` file. 

# Problems I am facing 
-  `cache_schema.rb` is using version 7.2, but schema.rb is using 8.0. So, maybe gem version is not configured correctly. 
- I couldn't create the `solid_cache_entries` from cache_schema.rb. I tried to ran `rails db:migrate`, `rails db:prepare` , `rails db:schema:load`. But none of those worked. 

If anyone has any suggestion on how to fix this issues, that will be of great help.

2024-12-26 16:03 UTC, pushcx commented
Sorry this took me a little time to respond to, I was sick and then traveling for the holiday.

Thank you for this and your other PRs. I’ll give them a full review on my next [office hours stream](https://push.cx/stream), you’re welcome to drop in to discuss them or just wait for comments.

2024-12-27 08:39 UTC, rahul1990gupta commented
Thanks for your response @pushcx . No rush. 
Hope that you get well soon and enjoy some time off during these holidays. 

I would have loved to drop in the office hours and chat, but that would be 1:30 am for me.  We can communicate asynchronously and take it from there.

2024-12-31 17:03 UTC, pushcx requested changes
Thanks, this looks great. I appreciate you taking on the setup tasks and, yeah, I'll give it a run before I put it into production.

2024-12-31 17:03 UTC, pushcx commented on config/cache.yml
> +  database: cache
Here and in `development`, can this move into the `default` section?

2024-12-31 17:53 UTC, pushcx commented on config/database.yml.sample
> +    database: storage/development_cache.sqlite3
```suggestion
    database: tmp/cache/cache.sqlite3
```

You can have your PR rm `storage/`, it's the file store we're replacing.

2024-12-31 17:53 UTC, pushcx commented on config/database.yml.sample
> +    adapter: trilogy
```suggestion
    adapter: trilogy
    encoding: utf8mb4
```

Not sure why this isn't present already, I'd rather make it a suggestion here than give you a merge conflict.

2024-12-31 17:57 UTC, pushcx commented on config/database.yml.sample
> +production:
Doesn't this need the `<<: *local`?

2024-12-31 18:03 UTC, pushcx commented on config/environments/development.rb
> +
```suggestion
```

Set this on line 31.

2025-01-01 07:10 UTC, rahul1990gupta commented on config/database.yml.sample
> +production:
there was no production config here before. I thought these were omitted because of security reasons. 

I will populate the fields then.

2025-01-02 05:56 UTC, rahul1990gupta commented
https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks

> By default, all first-time contributors require approval to run workflows.

2025-01-02 19:21 UTC, pushcx commented on config/database.yml.sample
> +production:
Your reorganization is clear and useful, excellent improvement!

2025-01-02 20:54 UTC, pushcx approved these changes

2025-01-02 20:55 UTC, pushcx commented
Looks like the build just needs a cache setup ("The `cache` database is not configured for the `test` environment.`") and this is ready to merge!

2025-01-03 01:39 UTC, rahul1990gupta commented
Yeah. This will need some hit and trial. Will see what can be done.

2025-01-03 08:56 UTC, rahul1990gupta commented
For this PR to go further either 
- CI will need to triggered autiomatically on push (without manual triggering)
- I setup my own runner server to run the workflow and iterate there.

2025-01-04 03:54 UTC, pushcx commented
Now that your other PR is merged, the build runs automatically for you.

2025-01-04 16:50 UTC, merged

2025-01-04 16:50 UTC, pushcx commented
Wonderful! Thank you for setting up this feature and working through all the config + build setup. I know that can get really fiddly and tedious.

2025-01-05 03:52 UTC, rahul1990gupta commented
Thank you, @pushcx for being patient with me through these set of PRs. I love that how you care about moderation on the platform, and spent so much effort grooming issues and reviewing PRs. This definitely makes contributing  approachable for a first-time open source contributor like me.