Sprockets to propshaft
lobsters/lobsters pull request #1410
Opened 2024-12-26 05:45 UTC by rahul1990gupta

This PR uses propshaft in place of sprockets for asset management and delivery. This is in line with rails 8's recommendation and as outlines in this issue https://github.com/lobsters/lobsters/issues/1366

This PR 
- Removes sprocket and uglifier. Adds importmap-rails and propshaft gems for javascript  and css delivery. 
- Changes application css from erb template to vanilla css file. 

Next Steps. 
- Break up aplication.css into website components: variables.css,story.css, comment.css, seatch.css. This will make it easier to maintain. 
-  Fix application.js.erb 
- Testing

2024-12-26 16:12 UTC, pushcx commented
I don’t want to split up the css into multiple files. I don’t see any benefit for a site this small.

Also, the `LIGHT` and `DARK` variables are there so users can override their browser’s default, see the references to `prefers_color_scheme`. I only glanced at the diff here but I think your change might break that. I’d love to reduce the duplication of having to print the `dark` colors twice and saw a mention on Bluesky that an expert thought it was possible, but I can’t find it again in the limited time I have this morning. I’ll have to keep looking.

2024-12-27 08:45 UTC, rahul1990gupta commented
The reason I suggested breaking up application.css to make the css more modular and with http 2, it is supported without any performance penalty. But i get it that benefits are mostly cosmetic and css  file is not that too large. 

A side question, what do you think about incorporating tailwindcss into the project ? It would be a larger rewrite of the css, but may make the UI more "modern".. maybe ? :D

2024-12-31 16:14 UTC, pushcx commented
Tailwind would reintroduce the nodejs dep I want to remove (or [other](https://tailwindcss.com/blog/standalone-cli) build complexity). It would add a new, big dependency to maintain and for potential contributors to learn. If you want a big css project, #1279 has one. But let's keep it separate from this PR!

2024-12-31 16:18 UTC, pushcx commented
I can't find the original article on reducing duplication in the dark and light versions of the CSS but [this article on light-dark](https://12daysofweb.dev/2024/css-light-dark/) has a design pattern that looks great. Probably also worth putting in a different PR than this build update!

2025-01-01 08:23 UTC, rahul1990gupta commented
Light-dark css property is great. Maybe will take it up in PR.

2025-01-01 11:03 UTC, rahul1990gupta commented
I was looking at the autosize.js javascript library used in the project and was wondering if is possible to replace these legacy libraries with something simple in modern html and js features. 

Will something like [this](https://codepen.io/rahul1990gupta/pen/PwYJdzw) capture all autosize.js functionalies.

2025-01-01 18:18 UTC, pushcx commented
So, I don’t think I’ve looked at that autosize js for years, I’m glad you took a fresh look at it. Reviewing, I think you’re right, we could drop that dependency and have just a little custom code for it.

It looks like you’ll need to add `word-wrap: break-word;` to the css (see `autosize.js` line 209). Otherwise a lot of the existing js works around layout issues we don’t have or events/lifecycle hooks we don’t need. Two things I don’t fully understand: 1. is there special behavior when the page resizes up or down? does the current library change autosize when the textarea is taller than the visible window and that resizes? 2. In `resize()`, what’s the purpose of the `scrollTop` code? Is it making sure it doesn’t feel like the textarea’s scroll position changes as the `textarea` changes size?

If you want to continue removing the library, please open a separate PR for removing it. I really look forward to it!

2025-01-02 20:05 UTC, pushcx commented on app/javascript/application.js
> +      'O': 'Off-topic', 'A': 'Already Posted', 'B': 'Broken Link', 'S': 'Spam', '': 'Cancel'
This (and `commentFlagReasons`) exist to avoid duplicating flags between the Vote model and here. Can you find another way to remove this duplication? Is there any negative to doing this with ERB?

2025-01-02 20:06 UTC, pushcx commented on vendor/javascript/.keep
I hate the Rails pluralization rules, but let's follow then and call this `vendor/javascripts`.

2025-01-03 01:50 UTC, rahul1990gupta commented on vendor/javascript/.keep
This was auto generated by `rails importmap:install` command. Changing this may cause other problems.

2025-01-03 16:58 UTC, pushcx commented on vendor/javascript/.keep
Well, my hate for the Rails pluralization rules is how I can never remember the arbitrary switching between singular and plural, so it's fitting that I'm wrong about this one. If this directory is what the generator gave you, that's what I want. Thanks for explaining.

2025-01-03 17:03 UTC, pushcx commented on app/javascript/application.js
> +      'O': 'Off-topic', 'A': 'Already Posted', 'B': 'Broken Link', 'S': 'Spam', '': 'Cancel'
Ah, thanks for explaining.

It was already a project to remove inline scripts from the site (#696 #697 #779) as a long-term security improvement, so I don't want to add one back.

One option would be to have the js be the authoritative list of flag reasons and have Rails parse it out at startup. Maybe it's because I'm mostly a backend developer, but that feels backwards and I don't want to do that.

I guess we only add and remove flags very infrequently. Please add a comment to this js explaining the reasons are duplicated in the Vote model, and add the reverse comment to Vote model.

2025-01-04 03:58 UTC, rahul1990gupta commented on app/javascript/application.js
> +      'O': 'Off-topic', 'A': 'Already Posted', 'B': 'Broken Link', 'S': 'Spam', '': 'Cancel'
Added the comments.

2025-01-06 21:27 UTC, pushcx commented on app/javascript/application.js
> +      'O': 'Off-topic', 'A': 'Already Posted', 'B': 'Broken Link', 'S': 'Spam', '': 'Cancel'
I talked this through on stream and someone pointed out that I misunderstood your suggestion. An easy way to remove this duplication would be to have an invisible html element with the flags in json and have the js load them. Now that I understand that, I think that's the best idea. Sorry I had you write comments.

We don't need to make it a standalone helper please add a `meta` tag in the `head`.

So I think that'll be `<meta name="storyFlags" content="<%=  Vote::STORY_REASONS.to_json ">` and something very similar for `commentFlags`.

2025-01-07 12:37 UTC, rahul1990gupta commented on app/javascript/application.js
> +      'O': 'Off-topic', 'A': 'Already Posted', 'B': 'Broken Link', 'S': 'Spam', '': 'Cancel'
I spent close to 2 hours making test work, but rspec is new to me. Will spend some more time later.

2025-01-13 22:03 UTC, pushcx requested changes
There's a bug with light and dark mode, if you work through those combinations of settings I'm ready to merge this.

2025-01-14 11:33 UTC, rahul1990gupta commented on app/assets/stylesheets/application.css
> +  html.color-scheme-system,
- [ ] browser set to light mode, no user setting (easy to test logged out) -> see light
- [ ] browser set to dark mode, no user setting (easy to test logged out) -> see dark
- [ ] browser set to light, user setting is 'system' -> see light
- [ ] browser set to dark, user setting is 'system' -> see dark
- [ ] browser set to light, user setting is 'dark' -> see dark
- [ ] browser set to dark, user setting is 'dark' -> see dark
- [ ] browser set to light, user setting is 'light' -> see light
- [ ] browser set to dark, user setting is 'light' -> see light

2025-01-14 12:17 UTC, rahul1990gupta commented on app/assets/stylesheets/application.css
> +  html.color-scheme-system,
my bad. it misses a case.

2025-01-14 12:17 UTC, rahul1990gupta commented
Testing after the commit.

- [ ] browser set to light mode, no user setting (easy to test logged out) -> see light
- [ ] browser set to dark mode, no user setting (easy to test logged out) -> see dark
- [ ] browser set to light, user setting is 'system' -> see light
- [ ] browser set to dark, user setting is 'system' -> see dark
- [ ] browser set to light, user setting is 'dark' -> see dark
- [ ] browser set to dark, user setting is 'dark' -> see dark
- [ ] browser set to light, user setting is 'light' -> see light
- [ ] browser set to dark, user setting is 'light' -> see light

2025-01-14 12:25 UTC, rahul1990gupta commented on app/assets/stylesheets/application.css
> +	/* main monochrome */
This is duplicated. I couldn't find a good way to reuse the variables and their values. 

On a side note, It will be nice to deprecate the user setting of light/dark mode and use the system settings, as most operating systems and browsers support it now. This will simplify the codebase as well.

2025-01-15 13:59 UTC, pushcx commented on app/assets/stylesheets/application.css
> +	/* main monochrome */
Did you look at [light-dark](https://12daysofweb.dev/2024/css-light-dark/)? I linked it earlier, maybe it would work for removing the duplication.

I don’t want to remove the user setting. I can’t claim to understand it, but people are feel very strongly about having it per-site.

2025-01-16 15:36 UTC, pushcx commented on app/assets/stylesheets/application.css
> +	/* main monochrome */
Yeah, I spent a minute reading the MDN page. In the [example section](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark#example) under the heading "CSS" they show moving all the variables into `:root`. Then an example of making a section of the page light mode, but rather than having a `.light` class to force the color scheme, we'd have `html.color-scheme-dark { color-scheme: dark; } html.color-scheme-light { color-scheme: light; }`.

I think that would solve this duplication.

2025-01-18 07:21 UTC, rahul1990gupta commented
Testing after the commit.

- [X] browser set to light mode, no user setting (easy to test logged out) -> see light
- [X] browser set to dark mode, no user setting (easy to test logged out) -> see dark
- [X] browser set to light, user setting is 'system' -> see light
- [X] browser set to dark, user setting is 'system' -> see dark
- [X] browser set to light, user setting is 'dark' -> see dark
- [X] browser set to dark, user setting is 'dark' -> see dark
- [X] browser set to light, user setting is 'light' -> see light
- [X] browser set to dark, user setting is 'light' -> see light

2025-01-20 20:44 UTC, pushcx commented
That's a really big refactor with light-dark, thanks for working through it and testing it against all those conditions.

This is ready to merge. My experience with the Rails asset pipeline is that every time I deploy a significant change, it breaks, but only in production. So I will wait to merge and deploy until this weekend. But I wanted to write to thank you for completing this project.

2025-01-20 20:44 UTC, pushcx approved these changes

2025-01-20 20:45 UTC, pushcx commented on app/assets/stylesheets/application.css
> +By default, in supporting browsers, the color returned by the light-dark() color function depends
Great comment explaining this functionality, thanks.

2025-01-25 09:23 UTC, rahul1990gupta commented
Tested it again after resolving the recent merge conflict. It is good to go. I will be checking my email this weekend regularly(morning/evening), in case deployment fails.

Let me know if anything else is needed.

2025-01-25 18:59 UTC, pushcx commented
Here goes nothing. 😄

2025-01-25 19:00 UTC, merged

2025-01-25 19:06 UTC, pushcx commented
Wow, I’m stunned. It deployed clean and Just Worked. Impressive work! Thank you again, Rahul.